/**
 * Generates env templates and docs from .env.schema.
 *
 * Usage:
 *   pnpm run env:generate              # writes to .env-preview/ (compare without overwriting)
 *   pnpm run env:generate --apply      # writes to real targets
 *
 * Targets:
 *   kodus-ai/.env.example
 *   kodus-ai/.env.template                    ← 1Password injection template (`op inject` source)
 *   kodus-installer/.env.example
 *   kodus-installer/scripts/schema-vars.sh   ← required-vars list, sourced by install.sh/doctor.sh
 *   kodus/docs/_snippets/env-vars-generated.mdx
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import {
    flatten,
    includesAudience,
    parseSchema,
    SchemaItem,
    SchemaSection,
} from './parse-schema';

const REPO_ROOT = join(__dirname, '..', '..');
const SCHEMA_PATH = join(REPO_ROOT, '.env.schema');

const APPLY = process.argv.includes('--apply');
// --installer flag writes ONLY the installer template; used by CI in the
// release workflow (which clones the kodus-installer repo into ./kodus-installer
// and runs `pnpm run env:apply --installer-out=../kodus-installer/.env.example`).
// Default `--apply` does NOT touch the installer — that's a cross-repo target.
const APPLY_INSTALLER = process.argv.includes('--installer');
const INSTALLER_OUT_ARG = process.argv.find((a) =>
    a.startsWith('--installer-out='),
);
const INSTALLER_OUT = INSTALLER_OUT_ARG
    ? INSTALLER_OUT_ARG.replace('--installer-out=', '')
    : join(REPO_ROOT, '..', 'kodus-installer', '.env.example');
const INSTALLER_SCHEMA_VARS_OUT_ARG = process.argv.find((a) =>
    a.startsWith('--installer-schema-vars-out='),
);
// Default the schema-vars path next to the installer-out, so the two
// generated artifacts ship together. CI passes both explicitly.
const INSTALLER_SCHEMA_VARS_OUT = INSTALLER_SCHEMA_VARS_OUT_ARG
    ? INSTALLER_SCHEMA_VARS_OUT_ARG.replace('--installer-schema-vars-out=', '')
    : join(REPO_ROOT, '..', 'kodus-installer', 'scripts', 'schema-vars.sh');
const POC_DIR = join(REPO_ROOT, '.env-preview');

const TARGETS = APPLY
    ? {
          envExample: join(REPO_ROOT, '.env.example'),
          envTemplate: join(REPO_ROOT, '.env.template'),
          // installer is excluded from `apply` — it's a different repo and
          // should only be regenerated by CI on release. Pass `--installer`
          // explicitly to write it (CI does this with --installer-out=...).
          installerEnv: APPLY_INSTALLER
              ? INSTALLER_OUT
              : join(POC_DIR, 'kodus-installer.env.example'),
          installerSchemaVars: APPLY_INSTALLER
              ? INSTALLER_SCHEMA_VARS_OUT
              : join(POC_DIR, 'kodus-installer.schema-vars.sh'),
          // docs lives inside this repo now (was a sister repo before).
          docsSnippet: join(
              REPO_ROOT,
              'docs',
              '_snippets',
              'env-vars-generated.mdx',
          ),
      }
    : {
          envExample: join(POC_DIR, 'kodus-ai.env.example'),
          envTemplate: join(POC_DIR, 'kodus-ai.env.template'),
          installerEnv: join(POC_DIR, 'kodus-installer.env.example'),
          installerSchemaVars: join(POC_DIR, 'kodus-installer.schema-vars.sh'),
          docsSnippet: join(POC_DIR, 'env-vars-generated.mdx'),
      };

const HEADER_KODUS_AI = `# AUTO-GENERATED from .env.schema. Do NOT edit by hand.
# Run \`pnpm run env:generate --apply\` after editing the schema.
# Source: kodus-ai/.env.schema
`;

const HEADER_INSTALLER = `# =============================================
# Kodus self-hosted environment file
# AUTO-GENERATED from kodus-ai/.env.schema. Do NOT edit by hand.
# Run \`pnpm run env:generate --apply\` in kodus-ai after editing the schema.
# =============================================
`;

const HEADER_TEMPLATE = `# AUTO-GENERATED from .env.schema. Do NOT edit by hand.
# Run \`pnpm run env:generate --apply\` after editing the schema.
#
# This is the 1Password injection template — the single source of truth
# for dev environment values. Materialize your local .env with:
#
#   pnpm run env:pull           # = op inject -i .env.template -o .env
#
# Secrets are pulled from the "Kodus-Dev" vault in 1Password (each item
# is named after its env var; the value lives in the "password" field).
# Non-secret defaults live inline here — edit the schema to change them.
#
# First-time setup: scripts/env/README.md (section: Pulling values from 1Password)
`;

// 1Password vault that holds dev secrets. Each env var maps to an item
// of the same name inside this vault, with the value stored in the
// "password" field. Change this constant if you rename the vault.
//
// NOTE: The vault name must NOT contain spaces — `op inject` parses
// secret refs as `op://<vault>/<item>/<field>` and splits on whitespace,
// so "Kodus Dev" breaks but "Kodus-Dev" works. Kebab-case is also the
// idiomatic 1Password convention for vault names referenced by op://.
const ONEPASSWORD_VAULT = 'Kodus-Dev';
const ONEPASSWORD_FIELD = 'password';

function renderEnvExample(sections: SchemaSection[]): string {
    const out: string[] = [HEADER_KODUS_AI];
    for (const section of sections) {
        const items = section.items.filter((it) =>
            includesAudience(it, 'cloud'),
        );
        if (items.length === 0) continue;
        out.push('');
        out.push(`# ============================================================`);
        out.push(`# ${section.title}`);
        out.push(`# ============================================================`);
        for (const item of items) {
            out.push(...renderItem(item, item.value, false));
        }
    }
    return out.join('\n') + '\n';
}

function renderEnvTemplate(sections: SchemaSection[]): string {
    const out: string[] = [HEADER_TEMPLATE];
    for (const section of sections) {
        const items = section.items.filter((it) =>
            includesAudience(it, 'cloud'),
        );
        if (items.length === 0) continue;
        out.push('');
        out.push(`# ============================================================`);
        out.push(`# ${section.title}`);
        out.push(`# ============================================================`);
        for (const item of items) {
            const value = templateValueFor(item);
            out.push(...renderItem(item, value, false));
        }
    }
    return out.join('\n') + '\n';
}

// Sensitive vars with no inline default get a 1Password ref. Sensitive
// vars that DO have a default (e.g. local-docker creds like
// API_PG_DB_PASSWORD=123456) keep the literal — they aren't real secrets,
// just well-known local fixtures, and putting them in 1P adds friction
// for zero gain.
function templateValueFor(item: SchemaItem): string {
    if (item.sensitive && item.value === '') {
        return `op://${ONEPASSWORD_VAULT}/${item.name}/${ONEPASSWORD_FIELD}`;
    }
    return item.value;
}

function renderInstallerEnv(sections: SchemaSection[]): string {
    const out: string[] = [HEADER_INSTALLER];
    for (const section of sections) {
        const items = section.items.filter((it) =>
            includesAudience(it, 'self-hosted'),
        );
        if (items.length === 0) continue;
        out.push('');
        out.push(`## ----  ${section.title.toUpperCase()}  ----`);
        for (const item of items) {
            const value = item.installerDefault ?? item.value;
            out.push(...renderItem(item, value, item.installerComment));
        }
    }
    return out.join('\n') + '\n';
}

function renderItem(
    item: SchemaItem,
    value: string,
    commentOut: boolean,
): string[] {
    const lines: string[] = [''];
    for (const desc of item.description) {
        lines.push(`# ${desc}`.trimEnd());
    }
    const hints: string[] = [];
    if (item.required) hints.push('required');
    if (item.sensitive) hints.push('secret');
    if (item.type) hints.push(`type: ${item.type}`);
    if (commentOut) hints.push('opt-in: uncomment to enable');
    if (hints.length > 0) {
        lines.push(`# (${hints.join(', ')})`);
    }
    const quoted = needsQuotes(value) ? `"${value}"` : value;
    const prefix = commentOut ? '# ' : '';
    lines.push(`${prefix}${item.name}=${quoted}`);
    return lines;
}

function needsQuotes(value: string): boolean {
    return /[\s#"']/.test(value);
}

function audienceBadge(item: SchemaItem): string {
    const isEE = item.audience.includes('self-hosted-enterprise');
    const others = item.audience.filter((a) => a !== 'self-hosted-enterprise');
    const eePrefix = isEE ? '🏢 ' : '';

    let base: string;
    if (others.length === 0) base = 'Self-hosted Enterprise';
    else if (others.includes('both'))
        base = item.installerComment ? '⚙️ Both (opt-in)' : '⚙️ Both';
    else if (others.includes('cloud') && !others.includes('self-hosted'))
        base = '☁️ Cloud';
    else if (others.includes('self-hosted') && !others.includes('cloud'))
        base = '🏠 Self-hosted';
    else base = others.join(' + ');

    return eePrefix + base;
}

function renderInstallerSchemaVars(sections: SchemaSection[]): string {
    const items = flatten(sections);
    const selfHosted = items.filter((it) => includesAudience(it, 'self-hosted'));

    // @required && audience self-hosted, EXCLUDING installer-comment=true
    // (those are opt-in commented in the template — the installer shouldn't
    // hard-fail when they're absent).
    const required = selfHosted
        .filter((it) => it.required && !it.installerComment)
        .map((it) => it.name);

    // Anything with a `kodus: autogen=<method>` annotation. The installer's
    // generate-secrets.sh iterates this list and produces a value via the
    // method when the var is empty.
    const autogen = selfHosted
        .filter((it) => it.autogen)
        .map((it) => `${it.name}=${it.autogen}`);

    const lines: string[] = [];
    lines.push('#!/usr/bin/env bash');
    lines.push('# AUTO-GENERATED from kodus-ai/.env.schema. Do NOT edit by hand.');
    lines.push('# Sourced by scripts/install.sh, scripts/doctor.sh, scripts/generate-secrets.sh');
    lines.push('# Run `pnpm run env:generate --apply --installer` in kodus-ai to regenerate.');
    lines.push('');
    lines.push('# Vars the installer must see set before booting the stack.');
    lines.push('# Derived from `@required` in the schema (self-hosted audience).');
    lines.push('KODUS_REQUIRED_VARS=(');
    for (const name of required) {
        lines.push(`    ${name}`);
    }
    lines.push(')');
    lines.push('');
    lines.push('# Secrets the installer can mint unattended.');
    lines.push('# Format: VAR=method  (hex32 | base64-32 | base64url-32 | mirror:OTHER_VAR)');
    lines.push('# Derived from `kodus: autogen=...` in the schema.');
    lines.push('KODUS_AUTOGEN_SECRETS=(');
    for (const entry of autogen) {
        lines.push(`    "${entry}"`);
    }
    lines.push(')');
    lines.push('');
    return lines.join('\n');
}

function renderDocsSnippet(sections: SchemaSection[]): string {
    const out: string[] = [];
    out.push('{/* AUTO-GENERATED from kodus-ai/.env.schema. Do NOT edit. */}');
    out.push('');
    for (const section of sections) {
        const items = section.items;
        if (items.length === 0) continue;
        out.push(`## ${section.title}`);
        out.push('');
        out.push('| Variable | Required | Type | Scope | Description |');
        out.push('| --- | --- | --- | --- | --- |');
        for (const item of items) {
            const required = item.required ? '✅' : '–';
            const type = item.sensitive
                ? `secret${item.type ? ` (${item.type})` : ''}`
                : item.type ?? 'string';
            // Escape backslash first (otherwise the next replace would
            // produce inconsistent escaping when descriptions contain
            // both `\` and `|`), then escape the markdown table delimiter.
            const desc = item.description
                .join(' ')
                .replace(/\\/g, '\\\\')
                .replace(/\|/g, '\\|');
            out.push(
                `| \`${item.name}\` | ${required} | ${type} | ${audienceBadge(item)} | ${desc} |`,
            );
        }
        out.push('');
    }
    return out.join('\n');
}

function ensureDir(filePath: string): void {
    mkdirSync(dirname(filePath), { recursive: true });
}

function main(): void {
    const sections = parseSchema(SCHEMA_PATH);
    const items = flatten(sections);

    const envExample = renderEnvExample(sections);
    const envTemplate = renderEnvTemplate(sections);
    const installerEnv = renderInstallerEnv(sections);
    const installerSchemaVars = renderInstallerSchemaVars(sections);
    const docs = renderDocsSnippet(sections);

    ensureDir(TARGETS.envExample);
    ensureDir(TARGETS.envTemplate);
    ensureDir(TARGETS.installerEnv);
    ensureDir(TARGETS.installerSchemaVars);
    ensureDir(TARGETS.docsSnippet);

    writeFileSync(TARGETS.envExample, envExample);
    writeFileSync(TARGETS.envTemplate, envTemplate);
    writeFileSync(TARGETS.installerEnv, installerEnv);
    writeFileSync(TARGETS.installerSchemaVars, installerSchemaVars);
    writeFileSync(TARGETS.docsSnippet, docs);

    const cloudCount = items.filter((it) => includesAudience(it, 'cloud')).length;
    const selfHostedCount = items.filter((it) =>
        includesAudience(it, 'self-hosted'),
    ).length;
    const requiredCount = items.filter((it) => it.required).length;
    const sensitiveCount = items.filter((it) => it.sensitive).length;

    console.log(`Parsed ${sections.length} sections, ${items.length} vars`);
    console.log(
        `  cloud:${cloudCount}  self-hosted:${selfHostedCount}  required:${requiredCount}  sensitive:${sensitiveCount}`,
    );
    console.log(`Mode: ${APPLY ? 'APPLY (real targets)' : 'POC (.env-preview/)'}`);
    console.log(`Wrote:`);
    console.log(`  ${TARGETS.envExample}`);
    console.log(`  ${TARGETS.envTemplate}`);
    console.log(`  ${TARGETS.installerEnv}`);
    console.log(`  ${TARGETS.installerSchemaVars}`);
    console.log(`  ${TARGETS.docsSnippet}`);
}

main();
