/**
 * Smoke: every component renders without throwing, with minimal props.
 */
import { render } from "@testing-library/react";
import { describe, it } from "vitest";

import {
    Alert,
    AlertDescription,
    AlertTitle,
    Avatar,
    AvatarStack,
    Badge,
    Breadcrumb,
    BreadcrumbCurrent,
    BreadcrumbLink,
    BreadcrumbSeparator,
    Button,
    Card,
    CardContent,
    CardFooter,
    CardHeader,
    Checkbox,
    ChoiceCard,
    ChoiceCards,
    Combobox,
    DescriptionItem,
    DescriptionList,
    EmptyState,
    ErrorCard,
    Field,
    FieldError,
    FieldHint,
    FilterChip,
    Heading,
    HelpTip,
    IndicatorDot,
    InlineCode,
    Input,
    Kbd,
    Label,
    LoadingState,
    Locked,
    Meter,
    MultiSelect,
    Navbar,
    NavbarActions,
    NavbarBrand,
    NavbarItem,
    NavbarNav,
    NumberInput,
    Page,
    PageHeader,
    PasswordInput,
    Progress,
    RadioGroup,
    RadioGroupItem,
    RequirementList,
    Section,
    Separator,
    SeparatorWithLabel,
    Setting,
    SettingsGroup,
    Sidebar,
    SidebarGroup,
    SidebarItem,
    SidebarScope,
    Skeleton,
    Slider,
    SliderWithMarks,
    Spinner,
    StatCard,
    StatCardRow,
    Steps,
    Switch,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableFooter,
    TableHead,
    TableHeader,
    TablePagination,
    TableRow,
    Tabs,
    TabsContent,
    TabsList,
    TabsTrigger,
    TagInput,
    Textarea,
    TextLink,
    Toaster,
    ToggleGroup,
    ToggleGroupItem,
    TooltipProvider,
    TreeFolder,
    TreeItem,
    TreeRoot,
} from "../src";

const noop = () => {};

const cases: Array<[string, React.ReactNode]> = [
    ["Alert", <Alert><AlertTitle>t</AlertTitle><AlertDescription>d</AlertDescription></Alert>],
    ["Avatar", <AvatarStack><Avatar online>GM</Avatar></AvatarStack>],
    ["Badge", <Badge variant="critical">Critical</Badge>],
    ["Breadcrumb", <Breadcrumb><BreadcrumbLink href="#">a</BreadcrumbLink><BreadcrumbSeparator /><BreadcrumbCurrent>b</BreadcrumbCurrent></Breadcrumb>],
    ["Button", <Button loading leftIcon={<span />}>go</Button>],
    ["Card", <Card><CardHeader>h</CardHeader><CardContent>c</CardContent><CardFooter>f</CardFooter></Card>],
    ["Checkbox", <Checkbox defaultChecked readOnly />],
    ["ChoiceCards", <ChoiceCards defaultValue="a"><ChoiceCard value="a" title="A" description="d" detail="x" badge="rec" /></ChoiceCards>],
    ["Combobox", <Combobox options={[{ value: "a", label: "A" }]} value="a" onValueChange={noop} clearable />],
    ["DescriptionList", <DescriptionList><DescriptionItem label="Path">**/*</DescriptionItem></DescriptionList>],
    ["EmptyState", <EmptyState icon="i" title="t" description="d" action={<Button>a</Button>} />],
    ["ErrorCard", <ErrorCard message="boom" onRetry={noop} />],
    ["ErrorCard inline", <ErrorCard variant="inline" message="boom" onRetry={noop} />],
    ["ErrorCard minimal", <ErrorCard variant="minimal" message="boom" />],
    ["Field", <Field><Label>l</Label><Input loading /><FieldHint>h</FieldHint><FieldError>e</FieldError></Field>],
    ["FilterChip", <FilterChip color="critical" count={2} onRemove={noop}>Critical</FilterChip>],
    ["Heading", <Heading level="display">h</Heading>],
    ["HelpTip", <TooltipProvider><HelpTip>help</HelpTip></TooltipProvider>],
    ["IndicatorDot", <IndicatorDot><Button size="icon">b</Button></IndicatorDot>],
    ["Input readOnly", <Input readOnly defaultValue="v" />],
    ["Input invalid", <Input aria-invalid defaultValue="v" />],
    ["Kbd/InlineCode", <p><Kbd>K</Kbd><InlineCode>c</InlineCode></p>],
    ["LoadingState", <LoadingState />],
    ["Locked", <TooltipProvider><Locked reason="nope"><Button disabled>x</Button></Locked></TooltipProvider>],
    ["Locked unlocked", <TooltipProvider><Locked locked={false}><Button>x</Button></Locked></TooltipProvider>],
    ["Meter", <Meter label="l" value={0.5} max={1} />],
    ["MultiSelect", <MultiSelect options={[{ value: "a", label: "A" }]} values={["a"]} onValuesChange={noop} />],
    ["Navbar", <Navbar><NavbarBrand>k</NavbarBrand><NavbarNav><NavbarItem active icon={<span />} badge={<span />}>i</NavbarItem></NavbarNav><NavbarActions>a</NavbarActions></Navbar>],
    ["NumberInput", <NumberInput value={3} onChange={noop} min={1} max={10} />],
    ["Page", <Page.Root><Page.Header><Page.TitleContainer><Page.Title>t</Page.Title><Page.HeaderActions>a</Page.HeaderActions></Page.TitleContainer><Page.Description>d</Page.Description></Page.Header><Page.Content>c</Page.Content><Page.Footer>f</Page.Footer></Page.Root>],
    ["PageHeader", <PageHeader title="t" description="d" actions={<Button>a</Button>} />],
    ["PasswordInput", <PasswordInput defaultValue="x" />],
    ["Progress", <Progress value={50} />],
    ["RadioGroup", <RadioGroup defaultValue="a"><RadioGroupItem value="a" readOnly /></RadioGroup>],
    ["RequirementList", <RequirementList title="t" requirements={[{ label: "8 chars", met: true }, { label: "1 num", met: false }]} />],
    ["Section", <Section title="t" description="d">c</Section>],
    ["Separator", <><Separator /><Separator dashed /><SeparatorWithLabel>or</SeparatorWithLabel></>],
    ["Settings", <TooltipProvider><SettingsGroup title="g" description="d"><Setting title="s" description="d" note="n" control={<Switch />} /><Setting title="locked" lockedReason="r" control={<Switch readOnly />} /></SettingsGroup></TooltipProvider>],
    ["Sidebar", <Sidebar><SidebarGroup label="g"><SidebarItem active icon={<span />} count={3}>i</SidebarItem><SidebarScope label="Global" count={2}><SidebarItem>sub</SidebarItem></SidebarScope></SidebarGroup></Sidebar>],
    ["Skeleton", <Skeleton className="h-4 w-20" />],
    ["Slider", <Slider defaultValue={[5]} min={0} max={10} />],
    ["SliderWithMarks", <SliderWithMarks marks={["a", "b"]} value={1} onValueChange={noop} />],
    ["Spinner", <Spinner size="lg" variant="muted" />],
    ["StatCard", <StatCardRow><StatCard icon="i" label="l" value="3.7M" hint="h" /></StatCardRow>],
    ["Steps", <Steps total={8} current={4} />],
    ["Switch", <Switch defaultChecked loading />],
    ["Switch readOnly", <Switch defaultChecked readOnly />],
    ["Table", <TableContainer><Table><TableHeader><TableRow><TableHead sort="asc" onSort={noop}>h</TableHead><TableHead>plain</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell numeric>1</TableCell><TableCell>x</TableCell></TableRow></TableBody></Table><TableFooter><TablePagination page={1} pageCount={12} onPageChange={noop} /></TableFooter></TableContainer>],
    ["Tabs", <Tabs defaultValue="a"><TabsList><TabsTrigger value="a" count={2}>A</TabsTrigger></TabsList><TabsContent value="a">c</TabsContent></Tabs>],
    ["TagInput", <TagInput tags={["a"]} onTagsChange={noop} placeholder="p" />],
    ["Textarea", <Textarea aria-invalid defaultValue="v" />],
    ["TextLink", <TextLink href="#">l</TextLink>],
    ["Toaster", <Toaster />],
    ["ToggleGroup", <ToggleGroup type="single" defaultValue="a"><ToggleGroupItem value="a">A</ToggleGroupItem></ToggleGroup>],
    ["Tree", <TreeRoot values={["x"]} onValuesChange={noop}><TreeFolder label="f"><TreeItem value="x">x</TreeItem></TreeFolder></TreeRoot>],
];

describe("smoke render", () => {
    it.each(cases)("%s", (_name, node) => {
        render(<>{node}</>);
    });
});
