// Verbatim claude-sonnet-4-5 responses (extended thinking, thinking blocks stripped
// as CustomStringOutputParser does) captured live for the @kody conversation bug.
// Each starts with a natural-language preamble before the fenced JSON — the exact
// shape that crashed parseLLMResponse in production (jsonrepair mangled it to an array).

export const SONNET_PROSE_RESPONSES: string[] = [
    "Sim, esse cron roda diariamente e verifica licenças que estão inativas há mais de X dias (geralmente configurável) para desativá-las automaticamente, mantendo a base limpa e evitando cobranças desnecessárias.\n\n```json\n{\n  \"reasoning\": \"O desenvolvedor quer entender o funcionamento do cron de inatividade de licenças. A resposta deve ser direta e resumida, explicando a frequência de execução (diária) e o propósito principal (desativar licenças inativas após um período configurável).\",\n  \"confidence\": 0.85,\n  \"action\": {\n    \"type\": \"final_answer\",\n    \"content\": \"Sim! Esse cron roda diariamente e verifica licenças que estão inativas há mais de X dias (geralmente configurável) para desativá-las automaticamente. O objetivo é manter a base limpa e evitar cobranças desnecessárias de licenças que não estão sendo usadas.\"\n  }\n}\n```",
    "Sim, o cron roda diariamente verificando licenças sem uso há mais de 30 dias (ou outro período configurado) e as desativa automaticamente para liberar slots.\n\n```json\n{\n  \"reasoning\": \"O desenvolvedor quer entender rapidamente a função e frequência do cron de inatividade de licenças implementado no PR #482. É importante confirmar a periodicidade (diária) e explicar brevemente o que ele faz (desativar licenças inativas após período configurado).\",\n  \"confidence\": 0.85,\n  \"action\": {\n    \"type\": \"final_answer\",\n    \"content\": \"Sim! O cron roda **diariamente** e desativa licenças que estão inativas há mais de X dias (geralmente 30 dias configurável). Ele busca licenças sem uso/login no período, marca como inativas e libera os slots automaticamente. Assim evita desperdício de licenças pagas que não estão sendo utilizadas. 🔄\"\n  }\n}\n```",
    "Sim, ele roda diariamente e desativa licenças que estão inativas há mais de X dias configurado.\n\n```json\n{\n  \"reasoning\": \"O desenvolvedor quer entender rapidamente a funcionalidade e frequência do cron de inatividade de licenças implementado no PR #482.\",\n  \"confidence\": 0.85,\n  \"action\": {\n    \"type\": \"final_answer\",\n    \"content\": \"Sim! O cron roda **diariamente** e verifica licenças que estão inativas por um período configurado (geralmente 30 ou 60 dias). Quando encontra licenças inativas além desse prazo, ele as desativa automaticamente para liberar slots e manter a base limpa. É uma rotina de housekeeping automática. 🧹\"\n  }\n}\n```"
];
