// environment.ts is generated by the Dockerfile via `sed` before build (see
// libs/ee/configs/environment/index.ts header). It does not exist in a clean
// checkout, so any spec that imports GithubService (or any of its DI
// dependencies that transitively pull in libs/ee/configs/environment) fails
// at module resolution. Mock it here so the cache tests can run locally
// without a build step. CI image already has the real environment.ts so it
// is a no-op there.
jest.mock(
    '../../../../../ee/configs/environment/environment',
    () => ({ environment: {} }),
    { virtual: true },
);

import { ConfigService } from '@nestjs/config';

import { GithubService } from './github.service';

/**
 * Focused cache-behavior tests for GithubService.
 *
 * Covers `getUserByUsername` only — the spec for `getFileWithContent`
 * would need a real Octokit instance (private method that receives the
 * octokit as a parameter), which collides with the heavy DI in this
 * service. Manual smoke + log inspection in QA covers that path.
 *
 * The point of this spec is to guard the cache contract:
 *   - cache hit returns without hitting Octokit
 *   - cache miss fetches and writes
 *   - 404 fetches, returns null, AND caches the null
 */

describe('GithubService — cache behavior', () => {
    const org = { organizationId: 'org-1', teamId: 'team-1' };

    const makeService = (overrides?: {
        cacheGet?: jest.Mock;
        cacheAdd?: jest.Mock;
        octokitGetByUsername?: jest.Mock;
    }) => {
        const cacheService = {
            getFromCache:
                overrides?.cacheGet ?? jest.fn().mockResolvedValue(null),
            addToCache:
                overrides?.cacheAdd ?? jest.fn().mockResolvedValue(undefined),
            removeFromCache: jest.fn(),
            clearCache: jest.fn(),
            cacheExists: jest.fn(),
            getMultipleFromCache: jest.fn(),
            deleteByKeyPattern: jest.fn(),
        };
        const integrationService = { findOne: jest.fn() };
        const authIntegrationService = {};
        const integrationConfigService = {
            createOrUpdateConfig: jest.fn(),
        };
        const configService = { get: jest.fn() } as unknown as ConfigService;

        const service = new GithubService(
            integrationService as any,
            authIntegrationService as any,
            integrationConfigService as any,
            cacheService as any,
            configService,
        );

        const octokit = {
            rest: {
                users: {
                    getByUsername:
                        overrides?.octokitGetByUsername ??
                        jest.fn().mockResolvedValue({
                            data: { id: 1, login: 'octocat' },
                        }),
                },
            },
        };
        jest.spyOn(service as any, 'instanceOctokit').mockResolvedValue(octokit);

        return { service, cacheService, octokit };
    };

    describe('getUserByUsername', () => {
        it('returns the cached value without hitting Octokit on a cache hit', async () => {
            const cached = { id: 99, login: 'cached-user' };
            const { service, cacheService, octokit } = makeService({
                cacheGet: jest.fn().mockResolvedValue(cached),
            });

            const result = await service.getUserByUsername({
                organizationAndTeamData: org,
                username: 'cached-user',
            });

            expect(result).toBe(cached);
            expect(cacheService.getFromCache).toHaveBeenCalledWith(
                'gh:user:org-1:cached-user',
            );
            expect(octokit.rest.users.getByUsername).not.toHaveBeenCalled();
            expect(cacheService.addToCache).not.toHaveBeenCalled();
        });

        it('fetches from Octokit and writes the result to cache on a miss', async () => {
            const { service, cacheService, octokit } = makeService();

            const result = await service.getUserByUsername({
                organizationAndTeamData: org,
                username: 'Octocat',
            });

            expect(result).toEqual({ id: 1, login: 'octocat' });
            // Key is lowercased — GitHub usernames are case-insensitive.
            expect(cacheService.getFromCache).toHaveBeenCalledWith(
                'gh:user:org-1:octocat',
            );
            expect(octokit.rest.users.getByUsername).toHaveBeenCalledWith({
                username: 'Octocat',
            });
            expect(cacheService.addToCache).toHaveBeenCalledWith(
                'gh:user:org-1:octocat',
                { id: 1, login: 'octocat' },
                24 * 60 * 60 * 1000,
            );
        });

        it('caches a null result for 404 (avoids re-hitting rate limit on missing users)', async () => {
            const notFound: any = new Error('Not Found');
            notFound.response = { status: 404 };
            const { service, cacheService, octokit } = makeService({
                octokitGetByUsername: jest.fn().mockRejectedValue(notFound),
            });

            const result = await service.getUserByUsername({
                organizationAndTeamData: org,
                username: 'ghost',
            });

            expect(result).toBeNull();
            expect(octokit.rest.users.getByUsername).toHaveBeenCalled();
            // Negative cache stored for 24h — same TTL as the positive
            // path. A deleted/nonexistent GitHub user doesn't reappear
            // within a working day, and a long null-cache saves the
            // round-trip when a stale reviewer is referenced repeatedly
            // across saves.
            expect(cacheService.addToCache).toHaveBeenCalledWith(
                'gh:user:org-1:ghost',
                null,
                24 * 60 * 60 * 1000,
            );
        });

        it('does NOT cache or swallow non-404 errors', async () => {
            const boom: any = new Error('rate limit');
            boom.response = { status: 403 };
            const { service, cacheService } = makeService({
                octokitGetByUsername: jest.fn().mockRejectedValue(boom),
            });

            await expect(
                service.getUserByUsername({
                    organizationAndTeamData: org,
                    username: 'octocat',
                }),
            ).rejects.toThrow('rate limit');
            expect(cacheService.addToCache).not.toHaveBeenCalled();
        });

        it('scopes cache by organization — same username in different orgs does NOT collide', async () => {
            const { service, cacheService } = makeService();

            await service.getUserByUsername({
                organizationAndTeamData: { organizationId: 'org-A', teamId: 't' },
                username: 'shared',
            });
            await service.getUserByUsername({
                organizationAndTeamData: { organizationId: 'org-B', teamId: 't' },
                username: 'shared',
            });

            const getCalls = (cacheService.getFromCache as jest.Mock).mock.calls.map(
                (c) => c[0],
            );
            expect(getCalls).toEqual([
                'gh:user:org-A:shared',
                'gh:user:org-B:shared',
            ]);
        });
    });
});
