export type PluginAuthScheme = "BEARER_TOKEN" | "API_KEY" | "OAUTH2" | "BASIC";

export enum MCP_CONNECTION_STATUS {
    ACTIVE = "ACTIVE",
    PENDING = "PENDING",
}

export const KODUS_MCP_GITHUB_ISSUES_INTEGRATION_ID =
    "kodus-github-issues-default";

export type CustomMCPPlugin = {
    id: string;
    name: string;
    description: string;
    authScheme: PluginAuthScheme;
    appName: string;
    logo: string;
    provider: string;
    isConnected: boolean;
};

export const CUSTOM_MCP_AUTH_METHODS = {
    NONE: "none",
    BEARER: "bearer_token",
    BASIC: "basic",
    API_KEY: "api_key",
    OAUTH2: "oauth2",
} as const;

export type CustomMCPAuthMethodType =
    (typeof CUSTOM_MCP_AUTH_METHODS)[keyof typeof CUSTOM_MCP_AUTH_METHODS];

export const CUSTOM_MCP_PROTOCOLS = {
    HTTP: "http",
    SSE: "sse",
} as const;

export type CustomMCPProtocolType =
    (typeof CUSTOM_MCP_PROTOCOLS)[keyof typeof CUSTOM_MCP_PROTOCOLS];

export const CUSTOM_MCP_SESSION_STORAGE_KEYS = {
    INTEGRATION_ID: "mcp_custom_integration_id",
    INTEGRATION_NAME: "mcp_custom_integration_name",
    PROVIDER: "mcp_custom_integration_provider",
} as const;

export enum IntegrationErrorCode {
    CLIENT_REGISTRATION_FAILED = "CLIENT_REGISTRATION_FAILED",
    INVALID_CLIENT = "INVALID_CLIENT",
    OAUTH_ERROR = "OAUTH_ERROR",
    VALIDATION_ERROR = "VALIDATION_ERROR",
}

export enum OAuthErrorCode {
    OAUTH_DISCOVERY_MISSING_AUTHORIZATION_SERVERS = "OAUTH_DISCOVERY_MISSING_AUTHORIZATION_SERVERS",
    OAUTH_DISCOVERY_FAILED_AUTHORIZATION_SERVER = "OAUTH_DISCOVERY_FAILED_AUTHORIZATION_SERVER",
    OAUTH_DISCOVERY_MISSING_ENDPOINTS = "OAUTH_DISCOVERY_MISSING_ENDPOINTS",
    OAUTH_CONFIG_MISSING_REDIRECT_URI = "OAUTH_CONFIG_MISSING_REDIRECT_URI",
    OAUTH_TOKEN_MISSING_ACCESS_TOKEN = "OAUTH_TOKEN_MISSING_ACCESS_TOKEN",
    OAUTH_INTEGRATION_NOT_FOUND = "OAUTH_INTEGRATION_NOT_FOUND",
    OAUTH_INTEGRATION_WRONG_AUTH_TYPE = "OAUTH_INTEGRATION_WRONG_AUTH_TYPE",
    OAUTH_METADATA_INCOMPLETE = "OAUTH_METADATA_INCOMPLETE",
    OAUTH_INVALID_STATE = "OAUTH_INVALID_STATE",
    OAUTH_TOKEN_EXCHANGE_FAILED = "OAUTH_TOKEN_EXCHANGE_FAILED",
}

export enum CustomIntegrationErrorCode {
    CUSTOM_INTEGRATION_MISSING_FIELDS = "CUSTOM_INTEGRATION_MISSING_FIELDS",
    CUSTOM_INTEGRATION_VALIDATION_FAILED = "CUSTOM_INTEGRATION_VALIDATION_FAILED",
    CUSTOM_INTEGRATION_EDIT_NOT_SUPPORTED = "CUSTOM_INTEGRATION_EDIT_NOT_SUPPORTED",
    CUSTOM_INTEGRATION_DELETE_NOT_SUPPORTED = "CUSTOM_INTEGRATION_DELETE_NOT_SUPPORTED",
    CUSTOM_INTEGRATION_HAS_ACTIVE_CONNECTIONS = "CUSTOM_INTEGRATION_HAS_ACTIVE_CONNECTIONS",
}
