export interface OutboxMessage {
    /**
     * Optional explicit UUID for the outbox message.
     * Note: outbox row UUID is generated by the database/ORM (PrimaryGeneratedColumn).
     */
    uuid?: string;
    /**
     * FK to `workflow_jobs(uuid)`. Required for messages emitted from a
     * workflow step so the relay can join back to the originating job.
     * Notification emits don't have a workflow job, so this is optional.
     */
    jobId?: string;
    exchange: string;
    routingKey: string;
    payload: Record<string, unknown>;
    /** When set, the outbox relay will not pick up this message until after this time. */
    nextAttemptAt?: Date;
}
