import { OrganizationAndTeamData } from '@libs/core/infrastructure/config/types/general/organizationAndTeamData';
import { CliReviewInput } from '@libs/cli-review/domain/types/cli-review.types';
import { PlatformType } from '@libs/core/domain/enums/platform-type.enum';

export interface CliReviewJobGitContext {
    remote?: string;
    branch?: string;
    commitSha?: string;
    /**
     * Merge-base between HEAD and the upstream default branch on the user's
     * machine. The sandbox checks out this commit (which is guaranteed to be
     * on the remote) and applies the diff on top, so reviews work for
     * branches that haven't been pushed yet and for uncommitted changes.
     */
    mergeBaseSha?: string;
    /**
     * Optional GitHub PAT (trial mode only). Sits in the job payload only
     * for the duration of the queue run — never persisted to automation
     * execution rows.
     */
    githubPat?: string;
    inferredPlatform?: PlatformType;
    cliVersion?: string;
}

/**
 * How the CLI request was authenticated. Persisted to dataExecution so the
 * dashboard can show "Team: <name>" or "Personal" without ever exposing the
 * key/token itself.
 */
export interface CliReviewJobAuthContext {
    mode: 'team-key' | 'personal';
    /** UUID of the team_cli_keys row when mode === 'team-key'. */
    teamKeyId?: string;
    /** Human label set by the user when generating the key. */
    teamKeyName?: string;
    /** Logged-in user UUID when mode === 'personal'. */
    userId?: string;
    /** Logged-in user email when mode === 'personal' (independent of git config). */
    userEmail?: string;
}

/**
 * Public-PR-demo metadata persisted alongside the job so the status
 * endpoint can serve the file/diff tree even when the original submit
 * happened in another browser session (shared link, refresh, etc).
 *
 * Only ever populated by POST /cli/public/review-pr. Authenticated CLI
 * flows leave this undefined.
 */
export interface CliReviewJobPublicPrMetadata {
    owner: string;
    repo: string;
    prNumber: number;
    title: string;
    state: 'open' | 'closed';
    merged: boolean;
    isDraft: boolean;
    headSha: string;
    headRef: string;
    baseSha: string;
    baseRef: string;
    additions: number;
    deletions: number;
    changedFiles: number;
    commitsCount: number;
    discussionCount: number;
    htmlUrl: string;
    author?: {
        login: string;
        avatarUrl?: string;
        htmlUrl?: string;
    };
    reviewers?: Array<{
        login: string;
        avatarUrl?: string;
        state: 'approved' | 'changes_requested' | 'commented' | 'pending';
    }>;
    checks?: {
        total: number;
        passed: number;
        failed: number;
        pending: number;
        conclusion: 'success' | 'failure' | 'partial' | 'pending' | 'unknown';
    };
    commits?: Array<{
        sha: string;
        message: string;
        authorLogin?: string;
        authorAvatarUrl?: string;
        authoredAt?: string;
        htmlUrl: string;
    }>;
    comments?: Array<{
        id: number;
        authorLogin?: string;
        authorAvatarUrl?: string;
        body: string;
        createdAt: string;
        htmlUrl: string;
        kind: 'issue' | 'review';
        path?: string;
        line?: number;
    }>;
    labels?: Array<{
        name: string;
        color?: string;
        description?: string;
    }>;
    assignees?: Array<{
        login: string;
        avatarUrl?: string;
        htmlUrl?: string;
    }>;
    body?: string;
    /** Markdown summary of the PR generated by a quick LLM call at
     *  enqueue time. Renders in the Description tab of the demo. */
    aiAnalysis?: string;
    /** Logical clusters of the changed files, also produced at enqueue
     *  time. Powers the "Grouped" view in the FileTree sidebar. */
    groupings?: Array<{
        title: string;
        explanation: string;
        files: string[];
    }>;
}

export interface CliReviewJobPayload {
    organizationAndTeamData: OrganizationAndTeamData;
    input: CliReviewInput;
    isTrialMode?: boolean;
    userEmail?: string;
    gitContext?: CliReviewJobGitContext;
    cliAuth?: CliReviewJobAuthContext;
    /** Public-demo only — see CliReviewJobPublicPrMetadata. */
    publicPr?: CliReviewJobPublicPrMetadata;
    /** Public-demo only — raw unified diff fetched from GitHub. */
    publicDiff?: string;
}
