// AUTO-GENERATED by scripts/feature-gate/generate-snapshot.ts.
// Do not edit by hand. Run `pnpm run feature-gate:snapshot` to regenerate.

import type { FeaturesSnapshot } from '../domain/snapshot.types';

export const FEATURES_SNAPSHOT: FeaturesSnapshot = {
    "schema_version": 1,
    "generated_at": "2026-07-07T14:47:56.505Z",
    "source": "manual",
    "features": {
        "github-enterprise-server-pat": {
            "name": "GitHub Enterprise Server (PAT auth)",
            "stage": "beta",
            "description": "Connect a GitHub Enterprise Server installation using a personal access token, for environments where the GitHub App flow isn't available.",
            "audience": [
                "cloud",
                "self-hosted"
            ]
        },
        "heavy-review": {
            "name": "Heavy review (deeper pass)",
            "stage": "alpha",
            "description": "An opt-in deeper review that re-runs the finder multiple times to surface more real bugs, for the changes where catching everything matters more than speed.",
            "audience": [
                "cloud",
                "self-hosted"
            ]
        }
    }
};
