// AUTO-GENERATED by scripts/feature-gate/generate-snapshot.ts.
// Do not edit by hand. Run `pnpm run feature-gate:snapshot` to regenerate.

import type { FeaturesSnapshot } from '../domain/snapshot.types';

export const FEATURES_SNAPSHOT: FeaturesSnapshot = {
    "schema_version": 1,
    "generated_at": "2026-06-16T16:39:33.332Z",
    "source": "manual",
    "features": {
        "github-enterprise-server-pat": {
            "name": "GitHub Enterprise Server (PAT auth)",
            "stage": "beta",
            "description": "Connect a GitHub Enterprise Server installation using a personal access token, for environments where the GitHub App flow isn't available.",
            "audience": [
                "cloud",
                "self-hosted"
            ]
        }
    }
};
